Allow running test suite without PAGINATOR set
kaminari is the default, so let's assume that. Otherwise, if PAGINATOR
is not set while running the test suite, you will always get a failure
like this:

  1) ApiPagination Using kaminari should accept paginate_array_options option
     Failure/Error: ApiPagination.config.paginator = ENV['PAGINATOR'].to_sym
     NoMethodError:
       undefined method `to_sym' for nil:NilClass
     # ./spec/api-pagination_spec.rb:13:in `block (3 levels) in <top (required)>'